//! CounterRepository — abstract persistence for the Counter aggregate.
//!
//! This trait is the **only** way the counter application layer talks to storage.
//! Implementations may use libsql, Turso cloud, SurrealDB, or in-memory stubs.

use async_trait::async_trait;
use chrono::{DateTime, Utc};

use super::super::domain::{Counter, CounterId};

/// Errors that can occur during repository operations.
///
/// This is intentionally generic — the repository implementation maps its
/// specific errors (SQL, HTTP, etc.) into this type.
pub type RepositoryError = Box<dyn std::error::Error + Send + Sync>;

/// Specifies a counter mutation operation for atomic commit.
///
/// Used by `commit_mutation` to execute CAS mutation + outbox write
/// + idempotency cache in a single atomic statement.
#[derive(Debug, Clone)]
pub enum CounterOperation {
    Increment,
    Decrement,
    Reset,
}

impl CounterOperation {
    pub fn as_str(&self) -> &'static str {
        match self {
            Self::Increment => "increment",
            Self::Decrement => "decrement",
            Self::Reset => "reset",
        }
    }
}

/// Full specification for an atomic counter mutation commit.
#[derive(Debug, Clone)]
pub struct CounterMutation<'a> {
    pub counter_id: &'a CounterId,
    pub operation: CounterOperation,
    pub new_value: i64,
    pub new_version: i64,
    pub event_id: &'a str,
    pub event_type: &'a str,
    pub event_payload: &'a str,
    pub source_service: &'a str,
    pub correlation_id: Option<&'a str>,
}

/// Result of an atomic counter mutation commit.
pub enum CommitOutcome {
    /// Mutation succeeded.
    Committed { new_value: i64, new_version: i64 },
    /// Idempotency key was already completed for the same request fingerprint.
    IdempotentReplay { value: i64, version: i64 },
    /// Idempotency key was reused for a different request fingerprint.
    IdempotencyConflict,
    /// CAS conflict: the counter was modified by another writer.
    CasConflict,
}

/// Abstract repository for Counter persistence with CAS support.
///
/// ## Responsibilities
/// - Store and retrieve Counter aggregates by CounterId
/// - Execute atomic increment/decrement/reset with CAS version check
/// - Write entries to the unified event_outbox
/// - Never leak business logic (no "default tenant" concepts here)
#[async_trait]
pub trait CounterRepository: Send + Sync {
    /// Load a counter by its ID. Returns None if not found.
    async fn load(&self, id: &CounterId) -> Result<Option<Counter>, RepositoryError>;

    /// Atomically increment a counter with CAS. Creates it if it doesn't exist.
    /// Returns (new_value, new_version) after increment.
    async fn increment(
        &self,
        id: &CounterId,
        expected_version: i64,
        now: DateTime<Utc>,
    ) -> Result<(i64, i64), RepositoryError>;

    /// Atomically decrement a counter with CAS.
    async fn decrement(
        &self,
        id: &CounterId,
        expected_version: i64,
        now: DateTime<Utc>,
    ) -> Result<(i64, i64), RepositoryError>;

    /// Reset a counter to zero with CAS.
    async fn reset(
        &self,
        id: &CounterId,
        expected_version: i64,
        now: DateTime<Utc>,
    ) -> Result<i64, RepositoryError>;

    /// Upsert a counter (used by application layer on first access).
    async fn upsert(&self, counter: &Counter) -> Result<(), RepositoryError>;

    /// Write an entry to the unified event_outbox.
    ///
    /// `event_id` is a UUID v7 generated by the application layer.
    async fn write_outbox(
        &self,
        event_id: &str,
        event_type: &str,
        payload: &str,
        source_service: &str,
        correlation_id: Option<&str>,
    ) -> Result<(), RepositoryError>;

    /// Atomically commit a counter mutation with CAS + outbox write + idempotency cache.
    ///
    /// Executes CAS counter update + event_outbox write in a single BEGIN/COMMIT
    /// transaction. If either the CAS mutation or outbox write
    /// fails, the entire transaction rolls back — no orphaned events, no phantom
    /// counter mutations.
    ///
    /// Idempotency reservation and completion run inside the same transaction as
    /// the mutation and outbox write. Reusing a key for a different request
    /// fingerprint returns `CommitOutcome::IdempotencyConflict`.
    ///
    /// Returns `CommitOutcome::CasConflict` when the expected_version doesn't match.
    async fn commit_mutation(
        &self,
        mutation: &CounterMutation<'_>,
        idempotency_key: Option<&str>,
    ) -> Result<CommitOutcome, RepositoryError>;
}
