// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Chat message sent event.
 */
export type ChatMessageSent = { conversation_id: string, message_id: string, sender_id: string, };
