// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Counter value changed event — emitted after a successful counter mutation.
 *
 * ## Dedupe rule (per model.yaml)
 * `tenant_id + counter_key + version`
 */
export type CounterChanged = { tenant_id: string, counter_key: string, operation: string, new_value: bigint, delta: bigint, version: bigint, };
