//! Authentication context middleware — extracts user_sub from JWT Bearer token.
//!
//! Environment-gated JWT verification:
//! - Dev mode (jwt_secret == "dev-secret-change-in-production"): insecure decode
//!   without signature verification (backward-compatible with Phase 6).
//! - Prod mode: full HS256 signature verification + exp claim validation.
//!
//! Extracts the JWT `sub` claim and injects request-scoped auth context.

use axum::{extract::Request, http::StatusCode, middleware::Next, response::Response};
use contracts_events::ActorRef;
use jsonwebtoken::{
    Algorithm, DecodingKey, Header, TokenData, Validation, dangerous::insecure_decode, decode,
    decode_header, jwk::JwkSet,
};
use observability::current_trace_context;
use serde::Deserialize;
use serde::de::DeserializeOwned;
use std::time::Duration;

use crate::config::Config;
use crate::error::BffError;

/// JWT claims — extracts Zitadel-compatible identity fields from the token.
///
/// In dev mode (MockOAuthProvider), these are generated by the mock.
/// In prod mode (Zitadel), these come from the IdP token.
#[derive(Debug, Deserialize)]
struct IdTokenClaims {
    sub: String,
    /// Tenant identifier — maps to Zitadel `urn:zitadel:iam:org:project:roles` custom claim.
    /// In dev mode, set by MockOAuthProvider.
    tenant_id: Option<String>,
    /// User roles — e.g., `["owner", "member", "admin"]`.
    /// Maps to Zitadel `roles` custom claim.
    roles: Option<Vec<String>>,
    /// Optional email claim for display/debug.
    email: Option<String>,
    aud: Option<serde_json::Value>,
    iss: Option<String>,
}

/// Request context extracted at the server boundary and forwarded into service calls.
#[derive(Debug, Clone)]
pub struct RequestContext {
    pub user_sub: String,
    pub tenant_id: Option<String>,
    pub roles: Vec<String>,
    pub request_id: Option<String>,
    pub trace_id: Option<String>,
    pub span_id: Option<String>,
    pub actor: ActorRef,
}

/// Default dev secret used by the boilerplate.
const DEV_SECRET: &str = "dev-secret-change-in-production";

/// Extract user_sub from Authorization: Bearer <token> and inject request context.
///
/// Reads `jwt_secret` from the BFF config in request extensions.
pub async fn tenant_middleware(mut req: Request, next: Next) -> Result<Response, BffError> {
    // 1. Read BFF config from the request extensions
    let config: Config = req
        .extensions()
        .get::<Config>()
        .cloned()
        .unwrap_or_default();

    if config.allows_dev_headers()
        && let Some(context) = dev_request_context(&req)
    {
        req.extensions_mut().insert(context);
        return Ok(next.run(req).await);
    }

    // 2. Extract Bearer token from Authorization header
    let token = req
        .headers()
        .get(axum::http::header::AUTHORIZATION)
        .and_then(|h| h.to_str().ok())
        .and_then(|h| h.strip_prefix("Bearer "))
        .ok_or_else(|| BffError::Unauthorized("Missing bearer token".to_string()))?;

    // 3. Decode JWT — Zitadel OIDC/JWKS, configured HS256, or dev insecure decode.
    let token_data = decode_token_claims(token, &config)
        .await
        .map_err(|_| BffError::Unauthorized("Invalid bearer token".to_string()))?;

    let subject = token_data.claims.sub.clone();
    let tenant_id = token_data.claims.tenant_id.clone();
    let roles = token_data.claims.roles.clone().unwrap_or_default();
    let request_id = req
        .headers()
        .get("x-request-id")
        .and_then(|value| value.to_str().ok())
        .map(str::to_owned);
    let trace_context = current_trace_context();

    // 4. Inject authenticated request context for downstream handlers.
    req.extensions_mut().insert(RequestContext {
        user_sub: subject.clone(),
        tenant_id,
        roles,
        request_id,
        trace_id: trace_context
            .as_ref()
            .map(|context| context.trace_id.clone()),
        span_id: trace_context.map(|context| context.span_id),
        actor: ActorRef {
            actor_id: subject.clone(),
            actor_type: "user".to_string(),
            subject: Some(subject),
        },
    });

    Ok(next.run(req).await)
}

fn dev_request_context(req: &Request) -> Option<RequestContext> {
    let user_sub = req
        .headers()
        .get("x-dev-user-sub")
        .and_then(|value| value.to_str().ok())?
        .trim()
        .to_string();
    if user_sub.is_empty() {
        return None;
    }

    let tenant_id = req
        .headers()
        .get("x-dev-tenant-id")
        .and_then(|value| value.to_str().ok())
        .map(str::trim)
        .filter(|value| !value.is_empty())
        .map(str::to_owned);
    let roles = req
        .headers()
        .get("x-dev-user-roles")
        .and_then(|value| value.to_str().ok())
        .map(parse_dev_roles)
        .unwrap_or_default();
    let request_id = req
        .headers()
        .get("x-request-id")
        .and_then(|value| value.to_str().ok())
        .map(str::to_owned);
    let trace_context = current_trace_context();

    Some(RequestContext {
        user_sub: user_sub.clone(),
        tenant_id,
        roles,
        request_id,
        trace_id: trace_context
            .as_ref()
            .map(|context| context.trace_id.clone()),
        span_id: trace_context.map(|context| context.span_id),
        actor: ActorRef {
            actor_id: user_sub.clone(),
            actor_type: "user".to_string(),
            subject: Some(user_sub),
        },
    })
}

fn parse_dev_roles(value: &str) -> Vec<String> {
    value
        .split(',')
        .map(str::trim)
        .filter(|item| !item.is_empty())
        .map(str::to_owned)
        .collect()
}

#[derive(Debug, Deserialize)]
struct OpenIdConfiguration {
    jwks_uri: String,
}

#[derive(Debug, Deserialize)]
struct IntrospectionResponse {
    active: bool,
    sub: Option<String>,
    username: Option<String>,
    aud: Option<serde_json::Value>,
    iss: Option<String>,
}

async fn decode_token_claims(
    token: &str,
    config: &Config,
) -> Result<TokenData<IdTokenClaims>, StatusCode> {
    if !config.zitadel_issuer.trim().is_empty() {
        if has_zitadel_introspection(config) {
            return introspect_zitadel_token(token, config).await;
        }
        return decode_zitadel_token(token, config).await;
    }

    if config.jwt_secret == DEV_SECRET {
        tracing::warn!(
            "BFF JWT: using insecure decode (dev-secret) — set APP_JWT_SECRET for production"
        );
        return insecure_decode::<IdTokenClaims>(token).map_err(|error| {
            tracing::debug!(error = %error, "BFF JWT insecure_decode failed");
            StatusCode::UNAUTHORIZED
        });
    }

    let mut validation = Validation::new(Algorithm::HS256);
    validation.validate_exp = true;
    validation.validate_aud = false;
    decode::<IdTokenClaims>(
        token,
        &DecodingKey::from_secret(config.jwt_secret.as_ref()),
        &validation,
    )
    .map_err(|error| {
        tracing::warn!(error = %error, "BFF JWT signature/exp validation failed");
        StatusCode::UNAUTHORIZED
    })
}

fn has_zitadel_introspection(config: &Config) -> bool {
    !config.zitadel_introspection_client_id.trim().is_empty()
        && !config.zitadel_introspection_client_secret.trim().is_empty()
}

async fn decode_zitadel_token(
    token: &str,
    config: &Config,
) -> Result<TokenData<IdTokenClaims>, StatusCode> {
    let header = decode_header(token).map_err(|error| {
        tracing::warn!(error = %error, "BFF JWT header decode failed");
        StatusCode::UNAUTHORIZED
    })?;

    let kid = header.kid.as_deref().ok_or_else(|| {
        tracing::warn!("BFF JWT missing kid while Zitadel issuer is configured");
        StatusCode::UNAUTHORIZED
    })?;

    let discovery_url = format!(
        "{}/.well-known/openid-configuration",
        config.zitadel_issuer.trim_end_matches('/')
    );
    let openid_config: OpenIdConfiguration = fetch_json(&discovery_url).await?;
    let jwks: JwkSet = fetch_json(&openid_config.jwks_uri).await?;
    let jwk = jwks.find(kid).ok_or_else(|| {
        tracing::warn!(kid, "BFF JWT kid not found in Zitadel JWKS");
        StatusCode::UNAUTHORIZED
    })?;
    let decoding_key = DecodingKey::from_jwk(jwk).map_err(|error| {
        tracing::warn!(error = %error, kid, "BFF JWT failed to build decoding key from JWKS");
        StatusCode::UNAUTHORIZED
    })?;

    let mut validation = Validation::new(header.alg);
    validation.set_issuer(&[config.zitadel_issuer.as_str()]);
    if config.zitadel_audience.trim().is_empty() {
        validation.validate_aud = false;
    } else {
        validation.set_audience(&[config.zitadel_audience.as_str()]);
    }

    decode::<IdTokenClaims>(token, &decoding_key, &validation).map_err(|error| {
        tracing::warn!(error = %error, issuer = %config.zitadel_issuer, "BFF Zitadel JWT validation failed");
        StatusCode::UNAUTHORIZED
    })
}

async fn introspect_zitadel_token(
    token: &str,
    config: &Config,
) -> Result<TokenData<IdTokenClaims>, StatusCode> {
    let introspection_url = format!(
        "{}/oauth/v2/introspect",
        config.zitadel_issuer.trim_end_matches('/')
    );
    let client = reqwest::Client::builder()
        .timeout(Duration::from_secs(5))
        .build()
        .map_err(|error| {
            tracing::warn!(error = %error, "BFF failed to build Zitadel introspection client");
            StatusCode::UNAUTHORIZED
        })?;
    let response = client
        .post(&introspection_url)
        .basic_auth(
            config.zitadel_introspection_client_id.as_str(),
            Some(config.zitadel_introspection_client_secret.as_str()),
        )
        .form(&[("token", token), ("token_type_hint", "access_token")])
        .send()
        .await
        .map_err(|error| {
            tracing::warn!(error = %error, url = %introspection_url, "BFF Zitadel introspection failed");
            StatusCode::UNAUTHORIZED
        })?;

    if !response.status().is_success() {
        tracing::warn!(status = %response.status(), url = %introspection_url, "BFF Zitadel introspection returned non-success");
        return Err(StatusCode::UNAUTHORIZED);
    }

    let body: IntrospectionResponse = response.json().await.map_err(|error| {
        tracing::warn!(error = %error, url = %introspection_url, "BFF Zitadel introspection decode failed");
        StatusCode::UNAUTHORIZED
    })?;

    if !body.active {
        tracing::warn!("BFF Zitadel introspection rejected inactive token");
        return Err(StatusCode::UNAUTHORIZED);
    }

    let sub = body.sub.or(body.username).ok_or_else(|| {
        tracing::warn!("BFF Zitadel introspection response missing subject");
        StatusCode::UNAUTHORIZED
    })?;

    if !config.zitadel_audience.trim().is_empty() {
        let audience_matches = match &body.aud {
            Some(serde_json::Value::String(value)) => value == &config.zitadel_audience,
            Some(serde_json::Value::Array(values)) => values.iter().any(|value| {
                value
                    .as_str()
                    .map(|item| item == config.zitadel_audience)
                    .unwrap_or(false)
            }),
            _ => false,
        };

        if !audience_matches {
            tracing::warn!(expected = %config.zitadel_audience, "BFF Zitadel introspection audience mismatch");
            return Err(StatusCode::UNAUTHORIZED);
        }
    }

    Ok(TokenData {
        header: Header::default(),
        claims: IdTokenClaims {
            sub,
            tenant_id: None,
            roles: None,
            email: None,
            aud: body.aud,
            iss: body.iss,
        },
    })
}

async fn fetch_json<T>(url: &str) -> Result<T, StatusCode>
where
    T: DeserializeOwned,
{
    let response = tokio::time::timeout(Duration::from_secs(5), reqwest::get(url))
        .await
        .map_err(|_| {
            tracing::warn!(url, "BFF OIDC fetch timed out");
            StatusCode::UNAUTHORIZED
        })?
        .map_err(|error| {
            tracing::warn!(error = %error, url, "BFF OIDC fetch failed");
            StatusCode::UNAUTHORIZED
        })?;

    if !response.status().is_success() {
        tracing::warn!(status = %response.status(), url, "BFF OIDC endpoint returned non-success");
        return Err(StatusCode::UNAUTHORIZED);
    }

    response.json::<T>().await.map_err(|error| {
        tracing::warn!(error = %error, url, "BFF OIDC JSON decode failed");
        StatusCode::UNAUTHORIZED
    })
}
