#ENC[AES256_GCM,data:FarZU1BlKQe7ZdZye1RTLEuWx0xkEEQ3aWJmb3T1Ad4dlfT82kCw4A9N,iv:2te9t9hvUHqOx3TsrHdxGw2wN0z4B8lIfEdIQU3z8fQ=,tag:ZBaeJs8/7zTj9OnJmgchhA==,type:comment]
#
#ENC[AES256_GCM,data:eL5Hwp9iGYOEk5hdlL50mb6MzNIEJ70SPSwiyr0wBmCHMQ8lMK0lvquI+MsHtkTuiuqbLg==,iv:Klzr3o4tIQbMiJiW6lKwOKFUnrHCLdvhgyMqrgCaT20=,tag:SgUQWJfnTi2keyE8HFz/MA==,type:comment]
#ENC[AES256_GCM,data:CfMNuQfMTRqo0Yct5oNKp3VRXaMVhmieDKdyi5albH5hPfeoBicFg+L1zuNFGEDZ9NLyM1G3Bjz/0fcCJ3S4AWydknlq9s+42ilWkZLMed65SL+kH1ijLsoDJzPG,iv:WlGETaDuECTi6g+prMhGP3+eBNdB3EkQHPjdEJWnqxc=,tag:kyQB8Gfb0TkI19bv1NBdeg==,type:comment]
#
#ENC[AES256_GCM,data:kmYFMrJO4eo8Ivpmth9jmaSPbIhFCgy66DHPZDP2ksg0inqxQsd+mRse0O115asuxbfaE1H2CItnIXeDn6eLBWw=,iv:KkKOXRXrh4M3aws3kW2Ce5VRCRbfp/ISRsoRBhYNG88=,tag:rGKqXq79QfduCBKexUpsMA==,type:comment]
apiVersion: ENC[AES256_GCM,data:zMY=,iv:EKgt7nVSm2X0xtmQvUnRPWNsntLJ+w+Xj557bFO3E7o=,tag:vGJVucwyJAzkgzoSDwRt3w==,type:str]
kind: ENC[AES256_GCM,data:v+EhqrNp,iv:phxYYLD+9HOZjv1SC8XLxZJDkshs4mbTj2lFMBekj/I=,tag:/pkT/SGv0PYvaqyY31jpdw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:gLIIJD0p5M1XjjJ05Ir+nX5QpRKiuTz1,iv:ZgzuUJpBV1vwrCcngC+w9wpCCejucVNj/hrD+oUUcOI=,tag:OXUPTwGEcQ1iSgnYbu9B+w==,type:str]
    namespace: ENC[AES256_GCM,data:oAWZ,iv:OiEOF5vL07K1ezd94J4YcpHeMqZdLumoOTQ5/N8L92w=,tag:Mf5Sv5VaBMyhWUyFQUysYA==,type:str]
    labels:
        app.kubernetes.io/name: ENC[AES256_GCM,data:2i4l7K8BxK9TGq9QL0YPjw==,iv:HgTyNe82WdwlFzyqtbhzrRf9o3fQQuum/xbhWKy4qAo=,tag:Xof/l+U/X6MA9KtstegKxg==,type:str]
        app.kubernetes.io/env: ENC[AES256_GCM,data:0NLo,iv:ilzKE7VHc5DrvmgU9U4+h3h/maHBrx1MIlp9RVr9pA8=,tag:Op3GgI4r2HDCfqjvf+vM0Q==,type:str]
type: ENC[AES256_GCM,data:ilofNnoD,iv:uyM1g8A9+/U+EvlirckuDGjSxG4dz88OnHsyPr97V4I=,tag:J8f/YTUnSSBHCSjGhA8oQw==,type:str]
stringData:
    #ENC[AES256_GCM,data:9zlSNAPsqwc/xoM2KMK/orDRZodXJwGjqoxkPBpMXvBN8rQtRRaX1um1dJJvTX6N4wDpsz8LRDuEnxS9Vx9Vsknpv0PC8fgUPxpqhUM/E+GRqTUA3TPMI0TvGBWgfLTKN654ICED4a56Ox5UaBVMfYWqtxP/xNyNJ53Ha6zByci/OAdPKMOCV/WhoSvus3TOkKGobFoqhjrbads=,iv:B8IctuTyYnpe6Ze9JwSkMM+YG4KX2kIVPAbAWfdCI+g=,tag:fHAOYmsW9QHk7p//fbaSvQ==,type:comment]
    #ENC[AES256_GCM,data:5VkMWu1N8qKG204IUgXAwgJpID28n6Elh0owCEevKGBZvuG0x5RzloYkjsTPHo9guwnXw1bLLmSTH5w=,iv:xNUr0a3BRNAR7rDeuRMVYPtnFdMnD1GtNSxEPRRQ0KM=,tag:1N5iXpKISXDRLSGFcgTIPA==,type:comment]
    #ENC[AES256_GCM,data:TeYU9cfMHlfRf93IzvnIjxBmxV4YhPw3WfD+KVyfXolFn9Xvq5ej6xDoIjKHFZsL8KxfygO0pg0F+1if6jdWx0aECdj8zxJn09cOgg==,iv:UFCdtCTwnVtjSxCC/3oOVWa9wOM+bipKuIrMNr9jKEA=,tag:vdELqlZQn6PBjfCe0iic1A==,type:comment]
    #ENC[AES256_GCM,data:rQINIXllNNqLG4bIr5F3UVJuqUkkN2Snj69n/9hwjcLbRI2F,iv:zesDYq/vtvHnbX+jE0uPBE0wZYO2HyYzhonYKYAgzbI=,tag:UIimaRSiX9eVbVQJGbiXjg==,type:comment]
    PROJECTOR_DATABASE_URL: ENC[AES256_GCM,data:pmvaEAjzFtbh7DOSogw8PEFIe9j7,iv:iyNpDPE9/ygLScBzaEpvA1fkvgD+a+gmRm4mCTke00s=,tag:J3rFdAQ99MYIi+oGfSRlBA==,type:str]
    #ENC[AES256_GCM,data:TeXOeSG2/0jTuvDSoOdh8vP41em9/tEgIm/EomOOYa89xLxqydLu3bFDgWphbQC1JOMInPkMUw==,iv:0YVxk7EX/2LjHdoay/DCm5j+f1PikCfbdm6OBrV4dr8=,tag:L4fPxjsSbRxlWaudzC+aFA==,type:comment]
sops:
    age:
        - recipient: age1p5v7s6gpq7grkdgldlguha9x3z79lgwl8vhwppwjs0xvng2g84rs8j67pm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLRlVMRkk3UWxaNm9idGRH
            d2kwaStTNS9zMDJtVHlYdGpManpIVm9rMW1FCk5kekN6YVp6bkFtYWtMWi84TWhu
            NVIraThtWVpiZkc5d0xhVnhKTGlYTDgKLS0tIEZ1dXJGMVcwL2crMU1ZNjZMclFN
            dms0MVZTUnhlZE43aEhJTkpaaVB1RnMKLz6rJxqqZpeJnqxBJgSBITeUSowHziz2
            Xr91YmF1QEEtSDmoz70xXzE/YxxKxsV6fPzfeAQoDCArPTFa6uIm/Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-16T05:37:23Z"
    mac: ENC[AES256_GCM,data:Jcwl01A769TUIcFsoIyLpXnS20Fn9WyX1jUuBjeLWJ2lfrGrcHOpb2/uDLBVFxzGOZ9AR11djsDY/4fss4iCfSUmaTQ20raoGtvLAg1g/NXSm01eJWo0rMS4sF//rW1+4gOvJedhYrWBZgu2LNvKg8J/l+JxK0jwQJD1LCaUZ7Y=,iv:ujMl0cqsm47x/h+kBfaeIpnTcLzNbLmMMKDXfLz7qTI=,tag:SsI77x+hzCxSwU/tA3bOxQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
