#ENC[AES256_GCM,data:IQVwMLeuZr5HXzwU6EXUIRbYYbcDpPzq2sE7kGQe8QYY,iv:AkW9EJ7Q6v6Va42LYgQ1i18rPiQyPYfwtUaTkJ2wSkQ=,tag:QHDQVLzgVkJd6Xt2y6PQxw==,type:comment]
#
#ENC[AES256_GCM,data:ecBIymU9cJ+fyVltcb8t+gg5FzJPfpqDKAewSf6WRofDJCNZKrS1VSUFWV10BKhBWk/7dA==,iv:QSap6Lt2Q1mf4KQ2RnFgefCclxwtoArxcKxZMXiWTr4=,tag:XSU+LRJvGhrif4v7TWz1MA==,type:comment]
#ENC[AES256_GCM,data:f6cLmhfHGhfs5jSOZ2zjMNaf5RDqUd4m2lh6qgyMIyT9KNkfo7265VkBkz9sSgQ2TZfujlJzIPaBoALaatn1k2C+EM5w3IzvJ1IUcNvj8jZF4X9M,iv:hrfg5UUWRpUt7yjz0byRDH1ahjUqOSZikOqKi51BwEM=,tag:qHvu6XGsE/q8BU6pVZ2a8A==,type:comment]
#
#ENC[AES256_GCM,data:OTlwOze6o4xo1Z9Lel+XsbUgEuO+R6ArCibTWZucgzdgSfzHz5BxD5UC9CPSCjdS86S7JaecEf8=,iv:dkgyHGdZfy9x9Lnd78NXZSHRvy3WJ4byanQ7bOcNbjg=,tag:NHtBYaDjYDgzld251iFNFw==,type:comment]
apiVersion: ENC[AES256_GCM,data:ku0=,iv:i6SSu1fsd4Swx52ISfwNi3q3Q96XZWLfn++nsUd1c6Y=,tag:oqD99GqoRui0lCRrSzfWrA==,type:str]
kind: ENC[AES256_GCM,data:WFkJ9xLl,iv:CLh5ihOfNJmBuezTK52s9POqDBQ5WdxqFtN5F8e9pjs=,tag:NfRzMbjx7N2TBUBmy8nuVg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:9cBFojlnIvhRg4nktllY,iv:/2r80n58lulP8yi0aHMMDXGF/PbFzBLzCZbbWjPicRQ=,tag:l4aKdmWt7lc5P3656XjOyw==,type:str]
    namespace: ENC[AES256_GCM,data:PyUa,iv:gPkB8+umQbnctoriBnTLirNNtq3ExCk2IKLGwYPCdTc=,tag:m48DUjbPQC8UKx4+Zpz0JA==,type:str]
    labels:
        app.kubernetes.io/name: ENC[AES256_GCM,data:DBI2FeCcWg==,iv:R+0AGuPYk4AJWPN7d2cAoF/bGfa5uGGW+MT2e2fTEtA=,tag:Mzu5gWyz0iRGZR9t96skxQ==,type:str]
        app.kubernetes.io/env: ENC[AES256_GCM,data:fsUR,iv:57iTK3qcwlyE5SERwuzcO2SlK1dRnSvmc/IhIdJLS2s=,tag:atr6lqx3T+hGTfLFC46fbg==,type:str]
type: ENC[AES256_GCM,data:OHPdT9er,iv:SPX1mVV9g01l26nIM2Oxdo02whekSGgVkeb2kbSufx8=,tag:FaKlRj4X+Br6YFt35i2hbw==,type:str]
stringData:
    #ENC[AES256_GCM,data:w0cvgaxQlWJKKVqds2W8IoMV4fCB4QOAD528Sf+BspZehMffUmUnYCFK3eVKU6Z0aNeMmMk+2NbSYNryaTY3ZoDqCWb/ctaAaKjpMg6mO5rntqtDNL7wa5Jme9qt0eteTBFe2rk9up/qwo7hZSE1EDtfjAXXZ1B+8PZR81evsfDBEnAauva1jcxe/qb7B9W+QVqozKhSF+12Uuu2uB3V5b3u,iv:lrX1ynw+Ya1si8vXaFvlRb0c3cwikGw/y7QHlGa1xKg=,tag:vlrkYDHgn1TDEEn/oOCtKQ==,type:comment]
    APP_SERVER_HOST: ENC[AES256_GCM,data:rYURDxqW+g==,iv:xRq41g1U27WpjaGjR95AEvtVELpad3mbYmeb1gN/kXg=,tag:T8+1TrQCXuNNBv2iLNGEnw==,type:str]
    APP_SERVER_PORT: ENC[AES256_GCM,data:60v3ew==,iv:x4fgcBVBhU51mIYLUw1Q6w9b4iy/hAUDoIzuarzJ4ik=,tag:LxbwuuLhToKGYrsv9jOddA==,type:str]
    APP_RUST_LOG: ENC[AES256_GCM,data:r8B5cSN65jpOsyFzH6pobclUrg==,iv:Wpei+rwlR8Ovjlm5avKzTJFJsvsqGNh2Gfvmmh9Lkrg=,tag:0NYCFlRZnCs19LSsAEb75A==,type:str]
    #ENC[AES256_GCM,data:N+sSDZyYZErz37DSltnUk5W4xh0sc6Jz3HmavFSlLUSBLEyEGho1/IP5D5j1ODpbsubxyEwbV8aAoPai8UmL0Hey134VltzqLzEazXohnC3WjQig4FUORTn9zea/t7GzskfDurwbr0w/XUqKARFyK8kNF1G65Hda7zJcsQTDwGQYdeE4ixF7kkMh,iv:f9q53NRO58TQxcoqoG36cPEZXAMBfiV6+pBUQuEZdK0=,tag:iMfFIH8fANF3XKNbyg0UZg==,type:comment]
    APP_JWT_SECRET: ENC[AES256_GCM,data:j7GrrJ5IDaq6GjUO5RkRCa4XtCBvPuee,iv:IooyCepm0+HypnktsaqvcVcG5Ol8do7rNSyljMc9sGY=,tag:QAsF3eijD4TTpv+sDQffkg==,type:str]
    #ENC[AES256_GCM,data:7GjM4GKX4N+d+AkhgQf61yRkcfpB01PmtqUvlqjGFQwBGFM5UnxBgkMhnHKiYRaIosF3kQEUdkp52g8eXfSWCw0QGJjl3fzS7H2qZ7UXvkPG7ui39/PG19C4VXa8RhFe2rm0nqeg9zuAvhjlPDVXvmXLH2xQlRsL4craKomTNYDSxbWxDI/SSYvQcSjDIFOLtM8D2rKSza9AKPAhKn8Hh3vEiZsA5g==,iv:5FSWO8dwCrku0t4o9MAtKA4UVWxGshTI8cXt0rBTUOA=,tag:iEALgyt+WsSRFtvqPtWYow==,type:comment]
    APP_CORS_ALLOWED_ORIGINS: ENC[AES256_GCM,data:QHaTmc2Lybab2+6s+bRnmLhzaCc8wZlWcd0o00NcT35J6y5y0yRQK/RLGA==,iv:TwAyjXlmoI/Eqy5flZUP7S6sp0S4jZAXBJO9iR2LIjg=,tag:E6WsHYgC9EIKG6pNLJrnnw==,type:str]
    #ENC[AES256_GCM,data:0ME4S+sMKN+cSjDRVMW6M3UeDle/t/Tt0ICl9gKsiJ6NiMaBoEzs4+ISv3tQfcKNVTB55vC9dQokbO98UXcMc7aR,iv:XesR8edqL/KrNiNg+xazeK6Z9VDnGpRLsmpQjLo7TPs=,tag:nBrE2a4qboFqqrAgapd9iA==,type:comment]
    APP_DATABASE_URL: ENC[AES256_GCM,data:q/ijfb5n/5DLb+pXGdkfWMo6zm/C,iv:rEN+V6j5gt5S8LW41jRFjmoWd0vt0TTjn3y+NcJmEkk=,tag:MuqBUQABsTOMWL1s52VUjQ==,type:str]
#ENC[AES256_GCM,data:57Acl/lUsTcroqDynhF02bbxKy5zKWd4985f97C1SCOPOKBa2s6rCxDs9A/jKG1qjrSFD0gwpvnaV1MvlaqSgCcgCYg=,iv:8xZCmyYURgU0ugvOFGxMiIwfi5Dgfc/2ewl1Wk7Qj8c=,tag:P8Ht597e/RTydDkG8rdwVA==,type:comment]
#ENC[AES256_GCM,data:gWx7u7oTUE/UfAIrOBCSW6Xq,iv:Z12Oat++PDbOSo5jHv5kHqhvTdnzvIVwnzW7BCmONl8=,tag:Hp4993kkax++cU/3qImopg==,type:comment]
#ENC[AES256_GCM,data:73yGju0j+yBpl8d3mVq/T4RQm9NPAwFOqg==,iv:99Lyqcgw9FUwVg+ucJ3cZRoJl5rUzci/IGfXjpl79ls=,tag:CeK641bBPN/19x4HozucLQ==,type:comment]
sops:
    age:
        - recipient: age1p5v7s6gpq7grkdgldlguha9x3z79lgwl8vhwppwjs0xvng2g84rs8j67pm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuZHErSXlwTEtTZ0IrUUJz
            NkxHZ0RKamZkRll6QXFZSDhOalY3dWJOa3pzCmc5cldHbHV2RXVZL2V3ZUVNSllI
            R3gvWFUzZTFJNEdOZVh0djVyejUvTjAKLS0tIDhpcGplSW1uc1BmRE5tWThlcDA5
            MFZZb25hMkZKOUtCSkJjMkl1d2ZnVG8KDRp+f0gqD0owqzOtd1g8OpW4t0m+/Ocr
            j3Jb2NFlRKPE0chKuc4qFM7/QdsN8AnmlmmVJR9jMS1wAzHV/qIt2A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-16T11:09:59Z"
    mac: ENC[AES256_GCM,data:H36aDcvzoO9qqmioUaovnlKXIWhVUI+ub1lMpeh37grSwDmOLMW9MBt7VYTmTh1TBI56+zsmDSl+9hCJ3QYtSmjeECJzQ49M3QTPBZtyyFNpk24XsL6cKi4BpdNdEfA1dAlkWzhxs6i+fV6AgMB741clx+buOFVo+W1OUlaNgnw=,iv:X1To8jO6u6aYLMUVEBBQ2Qfgo6ABN0uvEzKNdnipMPg=,tag:WrVF46ietiHL2PErwtkurg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
