// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChatMessage } from "./ChatMessage";

/**
 * Agent conversation with messages.
 */
export type ConversationDetail = { id: string, title: string, messages: Array<ChatMessage>, };
