// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Generic counter operation response.
 */
export type CounterResponse = { 
/**
 * The current counter value after the operation.
 */
value: bigint, };
