// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Request body for creating an agent conversation.
 */
export type CreateConversationRequest = { 
/**
 * Conversation title.
 */
title: string, };
