// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Response from tenant initialization.
 */
export type InitTenantResponse = { 
/**
 * The tenant ID in "table:key" format.
 */
tenant_id: string, 
/**
 * User's role within the tenant.
 */
role: string, 
/**
 * Whether a new tenant was created.
 */
created: boolean, };
