// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * OAuth callback payload from provider.
 */
export type OAuthCallback = { code: string, state: string, };
