// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Agent configuration (user-provided API key + endpoint).
 */
export type AgentConfig = { 
/**
 * API key — skipped during serialization to prevent accidental exposure.
 */
api_key: string, base_url: string, model: string, };
