// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "../serde_json/JsonValue";

/**
 * Tool call in a chat message.
 */
export type ToolCall = { id: string, name: string, arguments: JsonValue, result: string | null, };
